Entity/ContactDetail.php
<?php
/**
 * @noinspection PhpUnused
 * @noinspection PropertyCanBePrivateInspection
 * @noinspection MethodShouldBeFinalInspection
 */

namespace OswisOrg\OswisAddressBookBundle\Entity;

use Doctrine\ORM\Mapping\Cache;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\Table;
use OswisOrg\OswisAddressBookBundle\Entity\AbstractClass\AbstractContact;
use OswisOrg\OswisCoreBundle\Entity\NonPersistent\Nameable;
use OswisOrg\OswisCoreBundle\Entity\NonPersistent\Publicity;
use OswisOrg\OswisCoreBundle\Interfaces\Common\NameableInterface;
use OswisOrg\OswisCoreBundle\Interfaces\Common\PriorityInterface;
use OswisOrg\OswisCoreBundle\Traits\Common\EntityPublicTrait;
use OswisOrg\OswisCoreBundle\Traits\Common\NameableTrait;
use OswisOrg\OswisCoreBundle\Traits\Common\PriorityTrait;

use function filter_var;
use function htmlspecialchars;

#[Entity]
#[Table(name: 'address_book_contact_detail')]
#[Cache(usage: 'NONSTRICT_READ_WRITE', region: 'address_book_contact')]
class ContactDetail implements NameableInterface, PriorityInterface
{
    use NameableTrait;
    use PriorityTrait;
    use EntityPublicTrait;

    /** Type of this contact detail. */
    #[ManyToOne(targetEntity: ContactDetailCategory::class, fetch: 'EAGER')]
    #[JoinColumn(name: 'category_id', referencedColumnName: 'id')]
    protected ?ContactDetailCategory $detailCategory = null;

    #[ManyToOne(targetEntity: AbstractContact::class, inversedBy: 'details')]
    #[JoinColumn(name: 'contact_id', referencedColumnName: 'id')]
    protected ?AbstractContact $contact = null;

    /** Text content of note. */
    #[Column(type: 'text', nullable: true)]
    protected ?string $content = null;

    public function __construct(
        ?ContactDetailCategory $category = null,
        ?string $content = null,
        ?Nameable $nameable = null,
        ?Publicity $publicity = null,
        ?AbstractContact $contact = null
    ) {
        $this->setContact($contact);
        $this->setDetailCategory($category);
        $this->setContent($content);
        $this->setFieldsFromNameable($nameable);
        $this->setFieldsFromPublicity($publicity);
    }

    public function getContact(): ?AbstractContact
    {
        return $this->contact;
    }

    public function setContact(?AbstractContact $contact): void
    {
        if ($this->contact && $contact !== $this->contact) {
            $this->contact->removeDetail($this);
        }
        $this->contact = $contact;
    }

    public function getFormatted(): ?string
    {
        if (null !== $this->getDetailCategory()) {
            return $this->getDetailCategory()->getFormatted(filter_var($this->getContent(), FILTER_SANITIZE_URL) ?: null,
                htmlspecialchars($this->getDescription()), htmlspecialchars(''.$this->getName()),);
        }

        return $this->getContent();
    }

    public function getDetailCategory(): ?ContactDetailCategory
    {
        return $this->detailCategory;
    }

    public function setDetailCategory(?ContactDetailCategory $detailCategory): void
    {
        $this->detailCategory = $detailCategory;
    }

    public function getContent(): ?string
    {
        if ($this->content && $this->isSpaceless()) {
            $this->content = preg_replace('/\s/', '', $this->content);
        }

        return $this->content;
    }

    public function setContent(?string $content): void
    {
        $this->content = $content && $this->isSpaceless() ? preg_replace('/\s/', '', $content) : $content;
    }

    public function isSpaceless(): bool
    {
        return $this->getDetailCategory()?->isSpaceless() ?? false;
    }

    public function getSchemaString(): ?string
    {
        return $this->detailCategory?->getContactSchema();
    }

    public function getCategoryString(): ?string
    {
        return $this->detailCategory?->getType();
    }

    public function getType(): ?string
    {
        return $this->getDetailCategory()?->getType();
    }

    public function getCategoryName(): ?string
    {
        return $this->detailCategory?->getName();
    }

    public function getShowInPreview(): bool
    {
        return $this->detailCategory?->getShowInPreview() ?? false;
    }
}

Form/PositionType.php
<?php
/**
 * @noinspection MethodShouldBeFinalInspection
 */

namespace OswisOrg\OswisAddressBookBundle\Form;

use OswisOrg\OswisAddressBookBundle\Entity\Organization;
use OswisOrg\OswisAddressBookBundle\Entity\Position;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\Exception\AccessException;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PositionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('organization', EntityType::class, [
            'label'    => false,
            'required' => false,
            'help'     => 'Vyberte organizaci.',
            'class'    => Organization::class,
        ]);
    }

    /**
     * @param  OptionsResolver  $resolver
     *
     * @throws AccessException
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Position::class,
            //                'attr' => ['class' => 'col-md-6'],
        ]);
    }

    public function getName(): string
    {
        return 'address_book_position';
    }
}

Resources/views/web/parts/about-us-info.html.twig
{% if organization is defined and organization %}
    <div class="row">
        <header class="col-lg-12 text-justify"><h2 class="text-uppercase">{{ organization.shortName }}</h2></header>
        <div itemprop="description" class="col-12">{{ organization.note|default('')|markdown_to_html }}</div>
    </div>
    <div class="row">
        <div class="col-lg-9">
            <p>
                <strong itemprop="legalName">{{ organization.name }}</strong>
                {% if organization.identificationNumber is defined and organization.identificationNumber %}
                    (IČ: <span itemprop="identifier">{{ organization.identificationNumber }}</span>)
                {% endif %}
            </p>

            {% for detail in organization.contactDetails %}
                {% if detail.contactType is defined and detail.contactType %}
                    <p>
                        <strong>{{ detail.name|default('Kontakt') }}:</strong>
                        {% autoescape false %}
                            {{ detail.formatted }}
                        {% endautoescape %}
                    </p>
                {% endif %}
            {% endfor %}

            <span itemprop="url" content="{{ organization.url }}"></span>
            <span itemprop="logo" content="'{{ absolute_url(asset('/images/contacts/'~organization.image)) }}"></span>
            <span itemprop="contactPoint" itemscope itemtype="http://schema.org/ContactPoint">
                    <span itemprop="contactType" content="customer service"></span>
                    <span itemprop="areaServed" content="CZ"></span>
                    <span itemprop="availableLanguage" content="cs"></span>
                    <span itemprop="email" content="{{ organization.email }}"></span>
                    <span itemprop="telephone" content="{{ organization.phone }}"></span>
                    <span itemprop="productSupported" content="{{ organization.name }}"></span>
                </span>
        </div>
        <div class="d-lg-none col-md-4 col-sm-3 col-xs-2 d-print-none"></div>
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-8 text-uppercase center-block text-center d-print-none">
            <div id="small-banner" style="background-image: url('{{ asset('/images/contacts/'~organization.image) }}')"></div>
        </div>
    </div>
{% endif %}

Resources/views/web/parts/about-us-profile.html.twig
<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12" title="{{ contact.nickname|default() }}">
    <article class="contact {{ contact.genderClass|default('') }}" id="{{ contact.slug|default('') }}"
             itemscope itemtype='{{ contact.person ? 'http://schema.org/Person' : 'http://schema.org/Organization' }}'>
        <div content="{{ asset('/images/contacts/'~contact.image) }}" class="contact-image-box text-uppercase"
             style="background-image: url({{ asset('/images/contacts/'~contact.image) }})" itemprop="image">
            <h3 itemprop="name">{{ contact.name }}</h3>
            {% for position in contact.positions %}
                {% if position.active and position.special %}
                    <h4 itemprop="jobTitle" class="text-uppercase" title="{{ position.name }}">{{ position.shortName }}</h4>
                {% endif %}
            {% endfor %}
        </div>
        <div class="first-line" title="{{ contact.description|default('')|markdown_to_html|striptags }}">
            {{ contact.description|default('')|markdown_to_html }}
        </div>
        <div itemprop="description">
            {{ contact.note|default('')|markdown_to_html }}
        </div>
    </article>
</div>

Resources/views/web/parts/about-us-profiles.html.twig
<!-- START: PROFILES -->
{% if organization.members|length > 0 %}
    {% for contact in contacts %}
        {% include '@ZakjakubOswisAddressBook/web/parts/about-us-profile.html.twig' %}
    {% endfor %}
{% else %}
    <div class="col-12">
        <p>Aktuálně nejsou k dispozici žádné kontakty k zobrazení.</p>
    </div>
{% endif %}
<!-- END: PROFILES -->

Resources/views/web/parts/breadcrumb-organization-parent.html.twig
{{- null -}}
{% if organization.parentOrganization is defined and organization.parentOrganization %}
    {% include '@OswisOrgOswisAddressBook/web/parts/breadcrumb-organization-parent.html.twig'
        with {'organization': organization.parentOrganization, 'b_active': false} %}
{% endif %}
{{- null -}}
{% include '@OswisOrgOswisCore/web/parts/breadcrumb-item.html.twig'
    with {
    'b_url': path('oswis_org_oswis_address_book_organization', {'slug': organization.slug}),
    'b_title': organization.shortName,
    'b_position': breadcrumb_index,
    'b_active': b_active|default,} %}
{{- null -}}

Resources/views/web/parts/organization-breadcrumbs.html.twig
{% extends '@OswisOrgOswisCore/web/parts/breadcrumbs.html.twig' %}

{% block breadcrumb_additional %}
    {% include '@OswisOrgOswisAddressBook/web/parts/breadcrumb-organization-parent.html.twig'
        with {'organization': organization, 'b_active': true} %}
{% endblock breadcrumb_additional %}
{% block breadcrumb_last %}
{% endblock breadcrumb_last %}

Resources/views/web/parts/organization-info.html.twig
{% if organization|default %}
    <div class="row">
        <header class="col-lg-12 text-start">
            <h2 class="text-uppercase">
                <i class="fas fa-users"></i>
                <span class="d-inline d-lg-none">{{ organization.shortName }}</span>
                <span class="d-none d-lg-inline">{{ organization.name }}</span>
            </h2>
        </header>
        <div itemprop="description" class="col-12">{{ organization.description|default|markdown_to_html }}</div>
        <div itemprop="description" class="col-12">{{ organization.note|default|markdown_to_html }}</div>
    </div>
    {% include '@OswisOrgOswisAddressBook/web/parts/organization-nav.html.twig' %}
    <div class="row">
        <div class="col-lg-9">
            <p>
                <strong itemprop="legalName">{{ organization.name }}</strong>
                {% if organization.identificationNumber|default %}
                    (IČ: <span itemprop="identifier">{{ organization.identificationNumber }}</span>)
                {% endif %}
            </p>
            {% for detail in organization.details|filter(d => d.publicOnWeb) %}
                <p class="mb-2">
                    <strong>{{ detail.categoryName|default('Kontakt') }}:</strong>
                    {% autoescape false %}{{ detail.formatted }}{% endautoescape %}
                </p>
            {% endfor %}
            <span itemprop="url" content="{{ organization.url }}"></span>
            <span itemprop="logo" content="'{{ absolute_url(asset('/images/contacts/'~organization.oneImage)) }}"></span>
            <span itemprop="contactPoint" itemscope itemtype="http://schema.org/ContactPoint">
                    <span itemprop="contactType" content="customer service"></span>
                    <span itemprop="areaServed" content="CZ"></span>
                    <span itemprop="availableLanguage" content="cs"></span>
                    <span itemprop="email" content="{{ organization.email }}"></span>
                    <span itemprop="telephone" content="{{ organization.phone }}"></span>
                    <span itemprop="productSupported" content="{{ organization.name }}"></span>
                </span>
        </div>
        <div class="d-lg-none col-md-4 col-sm-3 col-xs-2 d-print-none"></div>
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-8">
            {{ render_hinclude(controller('OswisOrg\\OswisCoreBundle\\Controller\\Web\\WebBannerController::showWebBanner',
                {'type': 'organization', 'identifier': organization.slug})) }}
        </div>
    </div>
{% endif %}

Resources/views/web/parts/organization-nav.html.twig
<nav>
    <div class="badges clearfix text-wrap mb-3 font-1-5rem">
        {% if organization.parentOrganization|default %}
            <a href="{{ path('oswis_org_oswis_address_book_organization', {'slug': organization.parentOrganization.slug}) }}" class="badge badge-warning"
               data-toggle="tooltip"
               itemprop="parentOrganization" content="{{ organization.parentOrganization.name }}" title="{{ organization.parentOrganization.name }}">
                <i class="fas fa-arrow-up"></i> {{ organization.parentOrganization.shortName }}
            </a>
        {% endif %}
        {% for subOrganization in organization.subOrganizations|default %}
            <a href="{{ path('oswis_org_oswis_address_book_organization', {'slug': subOrganization.slug}) }}" class="badge badge-light" data-toggle="tooltip"
               itemprop="subOrganization" content="{{ subOrganization.name }}" title="{{ subOrganization.name }}">
                <i class="fas fa-sitemap"></i> {{ subOrganization.shortName }}
            </a>
        {% endfor %}
    </div>
</nav>

Resources/views/web/parts/organization-person-profile.html.twig
{% set imgSrc = preload(asset(contact.oneImage ? '/images/contacts/'~contact.oneImage : 'assets/images/seznamovak/kytka-512-upscale.png'), {as: 'image'}) %}

<div class="col"
     title="{{ contact.nickname|default(contact.name|default) }}"
     itemprop="member"
     data-bs-toggle="tooltip"
     itemscope
     itemtype='{{ 'http://schema.org/' ~ (contact.person ? 'Person' : 'Organization') }}'>

    <article class="card profile {{ contact.gender|default }} border-0 h-100 m-1"
             id="person-profile-{{ contact.slug|default(contact.id) }}">
        <div style="background-image: url({{ imgSrc }}) !important; background-position: center; background-repeat: no-repeat; background-size: cover;"
             itemprop="image"
             class="card-img rounded rounded-3 ratio ratio-1x1 "
             content="{{ imgSrc }}">
            <div class="card-img-overlay">
                {% if position.active and position.special %}
                    <h4 itemprop="jobTitle"
                        data-bs-toggle="tooltip"
                        title="{{ position.name|default }}"
                        content="{{ position.name|default }}"
                        class="card-subtitle text-uppercase top-0 start-0">
                        {{ position.shortName|default }}
                    </h4>
                {% endif %}
                <meta itemprop="alternateName" content="{{ contact.nickname|default(contact.givenName)|default }}">
                <h3 class="card-title text-uppercase position-absolute bottom-0 end-0 px-2" itemprop="name">{{ contact.name }}</h3>
            </div>
        </div>
        <div class="card-body px-0 py-1">
            <div itemprop="description"
                 class=" card-text first-line text-truncate"
                 title="{{ position.description|markdown_to_html }}"
                 data-bs-toggle="tooltip"
                 data-bs-html="true">
                {{ position.description|default|markdown_to_html }}
            </div>
            <div itemprop="description">
                {{ position.note|default|markdown_to_html }}
            </div>
        </div>
    </article>

</div>

Resources/views/web/parts/organization-person-profiles.html.twig
{% if positions|default and positions|length > 0 %}
    <div class="container-fluid">
        <header class="row">
            <div class="col-12 mt-5">
                <h3>Aktuální tým</h3>
            </div>
        </header>
        <main class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-1 g-md-2 g-lg-3 g-xl-4">
            {% for position in positions|sort((a, b) => b.priority <=> a.priority) %}
                {% include '@OswisOrgOswisAddressBook/web/parts/organization-person-profile.html.twig' with {'contact': position.person} %}
            {% else %}
                <div class="col-12 my-5">
                    <p>Aktuálně nejsou k dispozici žádné kontakty k zobrazení.</p>
                </div>
            {% endfor %}
        </main>
    </div>
{% endif %}